### ISSUE TITLE
译码阶段需要检查指令中的某些字段

### ISSUE THREAD

**Issue by iambingoNJU** [NJUCS-ComputerSystemLab-2017/NOOP#31]
举个例子：
  比如ADDU指令，在MIPS32手册上面，各个字段的含义为：
    +-----------+------+-----+------+-----+------------+
    + special  |  rs   |  rt   |  rd   |  0   |   ADDU   |
    +-----------+------+-----+------+-----+------------+
  现在的译码过程只看OP字段（special）和FUNC字段(ADDU)，但是ADDU指令要求SA字段（0）的值为0,我们并没有检查这个字段的值。因此，我们的译码检查并不严格，所以需不需要增加这个字段的检查？

**Comment by sashimi-yzh** [comment]
我覺得不需要, 編譯器應該不會編譯出SA字段不爲0的ADDU指令.

**Comment by iambingoNJU** [comment]
只用OP字段和FUNC字段是区分不了SRL指令和ROTR指令的，你看一下手册中的指令编码（顺便问一下，评论不可以直接贴照片吗）

**Comment by sashimi-yzh** [comment]
加個編譯選項, 不要編譯出新版的指令就可以了.

**Comment by iambingoNJU** [comment]
我的那个测试文件生成的指令开始都是mips32r2（release 2）指令，后来由于某些测试程序生成了SEB指令，现在都是生成mips32指令。不过在我们实现的指令集中这个问题确实不大，可以用脚本来检查指令是否实现。
